In [ ]:
### Insertando código Python

In [10]:
x = 10
y = 15
prom = (x+y)/2
print (prom)

12.5


In [3]:
### Trabajando con listas
A = [5.2,5.8,5.9]
## Recordemos funciones para trabajar listas
print(type(A))
print(len(A))
print(A)
A.append(10.9)
print(A)
A.clear()
print(A)
print(len(A))
A = [5.2,5.8,5.9,15.6,8.975]
A.count(5.2)
B=A.copy()
print(A)
print(B)
print(id(B))
print(id(A))
C=[2,3,6]
A.extend(C)
print(id(A))
id(5)
A.append(C)
print(A)


<class 'list'>
3
[5.2, 5.8, 5.9]
[5.2, 5.8, 5.9, 10.9]
[]
0
[5.2, 5.8, 5.9, 15.6, 8.975]
[5.2, 5.8, 5.9, 15.6, 8.975]
2372709761728
2372709472832
2372709472832
[5.2, 5.8, 5.9, 15.6, 8.975, 2, 3, 6, [2, 3, 6]]


In [35]:
A = [5.2,5.8,5.9,15.6,8.975]
print(A.index(15.6))
A.index(5.2)
A.insert(3,10)
A.pop()
A.remove(10)
print(A)
A.reverse()
print(A)
A.sort()
A


3
[5.2, 5.8, 5.9, 15.6]
[15.6, 5.9, 5.8, 5.2]


[5.2, 5.8, 5.9, 15.6]

In [5]:
print(id(5))
print(id(10))
A=[5,10]
print(id(A))
print(A[0])
print(A[1])
print(id(A[0]))
print(id(A[1]))                                                                        

140705056631352
140705056631512
2372709595264
5
10
140705056631352
140705056631512


In [6]:
print(A)
## i  es un elemento de la lista
s = 0
for i in A:
    s = s+ i                               
print(s)    

[5, 10]
15


In [7]:
## i es el index de la lista

S=0
for i in range(len(A)):
  S = S + A[i]
print(S)

type(A)
A.extend(["hola"])
A

15


[5, 10, 'hola']

In [8]:
type(A)
A.extend(["hola"])
A

[5, 10, 'hola', 'hola']

In [10]:
###importando librerías:
import numpy as np

A = [5.2,5.8,5.9]
Ar = np.array(A)
print(Ar)
print(sum(Ar))
media = np.mean(Ar)
print(media)
varianza = np.var(Ar)
print(varianza)
B = np.array([[1, 2, 3], [4, 5, 6]])
print(B)
print(np.mean(B[0]))
print(np.mean(B,axis=1))

print(np.mean(B,axis=0))
print(B.mean(axis=1))
print(B.mean(axis=0))
print(B[:,0].mean())                        

[5.2 5.8 5.9]
16.9
5.633333333333333
0.09555555555555555
[[1 2 3]
 [4 5 6]]
2.0
[2. 5.]
[2.5 3.5 4.5]
[2. 5.]
[2.5 3.5 4.5]
2.5


In [47]:
###importando librerías:
import numpy as np
Ar = np.array(A)
print(Ar)
type(Ar)

['5.2' '5.8' '5.9' '15.6' 'h' 'o' 'l' 'a' 'hola']


numpy.ndarray

In [12]:
!pip install pandas
import pandas

In [11]:
!echo "hola mundo"
!mkdir PRUEBA
!dir
!ver
!path
!cd

"hola mundo"
 El volumen de la unidad C es Windows 
 El n£mero de serie del volumen es: AE6E-7A74

 Directorio de C:\Users\usuario5810\Desktop\Notebooks

14/03/2025  11:43    <DIR>          .
14/03/2025  11:07    <DIR>          ..
14/03/2025  11:10    <DIR>          .ipynb_checkpoints
14/03/2025  11:08           111,484 Ficheros.ipynb
14/03/2025  11:08             8,226 notebookLatex.ipynb
14/03/2025  11:08             6,004 notebookMarkdown.ipynb
14/03/2025  11:43    <DIR>          PRUEBA
14/03/2025  11:36            18,774 RepasandoPython-JupyterNotebook (1).ipynb
               4 archivos        144,488 bytes
               4 dirs  392,758,669,312 bytes libres

Microsoft Windows [Versi¢n 10.0.22631.5039]
PATH=C:\Users\usuario5810\anaconda3;C:\Users\usuario5810\anaconda3\Library\mingw-w64\bin;C:\Users\usuario5810\anaconda3\Library\usr\bin;C:\Users\usuario5810\anaconda3\Library\bin;C:\Users\usuario5810\anaconda3\Scripts;C:\Users\usuario5810\anaconda3\bin;C:\Users\usuario5810\anaconda3

In [8]:
print(A)


[5.2, 5.8, 5.9]
